// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: river_pro_ext.sql

package dbsqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const jobDeadLetterDeleteByID = `-- name: JobDeadLetterDeleteByID :one
DELETE FROM /* TEMPLATE: schema */river_job_dead_letter
WHERE id = $1
RETURNING job
`

func (q *Queries) JobDeadLetterDeleteByID(ctx context.Context, db DBTX, id int64) ([]byte, error) {
	row := db.QueryRow(ctx, jobDeadLetterDeleteByID, id)
	var job []byte
	err := row.Scan(&job)
	return job, err
}

const jobDeadLetterGetAll = `-- name: JobDeadLetterGetAll :many
SELECT job
FROM /* TEMPLATE: schema */river_job_dead_letter
ORDER BY moved_at DESC
LIMIT $1
`

func (q *Queries) JobDeadLetterGetAll(ctx context.Context, db DBTX, max int32) ([][]byte, error) {
	rows, err := db.Query(ctx, jobDeadLetterGetAll, max)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items [][]byte
	for rows.Next() {
		var job []byte
		if err := rows.Scan(&job); err != nil {
			return nil, err
		}
		items = append(items, job)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const jobDeadLetterGetByID = `-- name: JobDeadLetterGetByID :one
SELECT job
FROM /* TEMPLATE: schema */river_job_dead_letter
WHERE id = $1
`

func (q *Queries) JobDeadLetterGetByID(ctx context.Context, db DBTX, id int64) ([]byte, error) {
	row := db.QueryRow(ctx, jobDeadLetterGetByID, id)
	var job []byte
	err := row.Scan(&job)
	return job, err
}

const jobDeadLetterUpsert = `-- name: JobDeadLetterUpsert :exec
INSERT INTO /* TEMPLATE: schema */river_job_dead_letter (id, job)
VALUES ($1, $2)
ON CONFLICT (id) DO UPDATE
SET job = EXCLUDED.job,
    moved_at = now()
`

type JobDeadLetterUpsertParams struct {
	ID  int64
	Job []byte
}

func (q *Queries) JobDeadLetterUpsert(ctx context.Context, db DBTX, arg *JobDeadLetterUpsertParams) error {
	_, err := db.Exec(ctx, jobDeadLetterUpsert, arg.ID, arg.Job)
	return err
}

const jobDeleteByIDManyReturningIDs = `-- name: JobDeleteByIDManyReturningIDs :many
DELETE FROM /* TEMPLATE: schema */river_job
WHERE id = any($1::bigint[])
RETURNING id
`

func (q *Queries) JobDeleteByIDManyReturningIDs(ctx context.Context, db DBTX, ids []int64) ([]int64, error) {
	rows, err := db.Query(ctx, jobDeleteByIDManyReturningIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const jobGetAvailableForBatch = `-- name: JobGetAvailableForBatch :many
WITH candidate_jobs AS (
    SELECT id
    FROM /* TEMPLATE: schema */river_job rj
    WHERE rj.queue = $3
      AND rj.kind = $4
      AND rj.state = 'available'
      AND rj.scheduled_at <= coalesce($1::timestamptz, now())
      AND coalesce(rj.batch_key, rj.metadata->>'batch_key', rj.kind) = $5
    ORDER BY rj.priority ASC, rj.scheduled_at ASC, rj.id ASC
    LIMIT $6
    FOR UPDATE SKIP LOCKED
)
UPDATE /* TEMPLATE: schema */river_job j
SET state = 'running',
    attempt = j.attempt + 1,
    attempted_at = coalesce($1::timestamptz, now()),
    attempted_by = array_append(coalesce(j.attempted_by, '{}'), $2)
FROM candidate_jobs c
WHERE j.id = c.id
RETURNING j.id
`

type JobGetAvailableForBatchParams struct {
	Now         *time.Time
	AttemptedBy interface{}
	Queue       string
	Kind        string
	BatchKey    pgtype.Text
	MaxToLock   int32
}

func (q *Queries) JobGetAvailableForBatch(ctx context.Context, db DBTX, arg *JobGetAvailableForBatchParams) ([]int64, error) {
	rows, err := db.Query(ctx, jobGetAvailableForBatch,
		arg.Now,
		arg.AttemptedBy,
		arg.Queue,
		arg.Kind,
		arg.BatchKey,
		arg.MaxToLock,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const jobGetAvailableLimited = `-- name: JobGetAvailableLimited :many
SELECT river_job_get_available_limited_ids
FROM /* TEMPLATE: schema */river_job_get_available_limited_ids(
    $1,
    coalesce($2::timestamptz, now()),
    $3,
    $4,
    $5,
    $6,
    $7,
    $8::text[],
    $9::text[],
    $10::integer[],
    $11::text[],
    $12
)
`

type JobGetAvailableLimitedParams struct {
	Queue                                 string
	Now                                   *time.Time
	GlobalLimit                           int32
	LocalLimit                            int32
	MaxToLock                             int32
	MaxAttemptedBy                        int32
	AttemptedBy                           string
	AvailablePartitionKeys                []string
	CurrentProducerPartitionKeys          []string
	CurrentProducerPartitionRunningCounts []int32
	PartitionByArgs                       []string
	PartitionByKind                       bool
}

func (q *Queries) JobGetAvailableLimited(ctx context.Context, db DBTX, arg *JobGetAvailableLimitedParams) ([]pgtype.Int8, error) {
	rows, err := db.Query(ctx, jobGetAvailableLimited,
		arg.Queue,
		arg.Now,
		arg.GlobalLimit,
		arg.LocalLimit,
		arg.MaxToLock,
		arg.MaxAttemptedBy,
		arg.AttemptedBy,
		arg.AvailablePartitionKeys,
		arg.CurrentProducerPartitionKeys,
		arg.CurrentProducerPartitionRunningCounts,
		arg.PartitionByArgs,
		arg.PartitionByKind,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.Int8
	for rows.Next() {
		var river_job_get_available_limited_ids pgtype.Int8
		if err := rows.Scan(&river_job_get_available_limited_ids); err != nil {
			return nil, err
		}
		items = append(items, river_job_get_available_limited_ids)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const jobGetAvailablePartitionKeys = `-- name: JobGetAvailablePartitionKeys :many
SELECT DISTINCT concat(
    CASE WHEN $1::boolean THEN kind ELSE '' END,
    '|',
    CASE
        WHEN $2::text[] IS NULL THEN ''
        WHEN cardinality($2::text[]) = 0 THEN args::jsonb::text
        ELSE coalesce((
            SELECT jsonb_object_agg(key, args->key ORDER BY key)
            FROM unnest($2::text[]) AS key
            WHERE args ? key
        ), '{}'::jsonb)::text
    END
)
FROM /* TEMPLATE: schema */river_job
WHERE queue = $3
  AND state = 'available'
  AND scheduled_at <= coalesce($4::timestamptz, now())
`

type JobGetAvailablePartitionKeysParams struct {
	PartitionByKind bool
	PartitionByArgs []string
	Queue           string
	Now             *time.Time
}

func (q *Queries) JobGetAvailablePartitionKeys(ctx context.Context, db DBTX, arg *JobGetAvailablePartitionKeysParams) ([]interface{}, error) {
	rows, err := db.Query(ctx, jobGetAvailablePartitionKeys,
		arg.PartitionByKind,
		arg.PartitionByArgs,
		arg.Queue,
		arg.Now,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []interface{}
	for rows.Next() {
		var concat interface{}
		if err := rows.Scan(&concat); err != nil {
			return nil, err
		}
		items = append(items, concat)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pGTryAdvisoryXactLock = `-- name: PGTryAdvisoryXactLock :one
SELECT pg_try_advisory_xact_lock($1::bigint)
`

func (q *Queries) PGTryAdvisoryXactLock(ctx context.Context, db DBTX, key int64) (bool, error) {
	row := db.QueryRow(ctx, pGTryAdvisoryXactLock, key)
	var pg_try_advisory_xact_lock bool
	err := row.Scan(&pg_try_advisory_xact_lock)
	return pg_try_advisory_xact_lock, err
}

const periodicJobDeleteStale = `-- name: PeriodicJobDeleteStale :many
DELETE FROM /* TEMPLATE: schema */river_periodic_job
WHERE updated_at < $1
RETURNING id, created_at, updated_at, name, queue, next_run_at, metadata
`

type PeriodicJobDeleteStaleRow struct {
	ID        int64
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	Queue     string
	NextRunAt time.Time
	Metadata  []byte
}

func (q *Queries) PeriodicJobDeleteStale(ctx context.Context, db DBTX, staleUpdatedAtHorizon time.Time) ([]*PeriodicJobDeleteStaleRow, error) {
	rows, err := db.Query(ctx, periodicJobDeleteStale, staleUpdatedAtHorizon)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*PeriodicJobDeleteStaleRow
	for rows.Next() {
		var i PeriodicJobDeleteStaleRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.Queue,
			&i.NextRunAt,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const periodicJobGetAllExt = `-- name: PeriodicJobGetAllExt :many
SELECT id, created_at, updated_at, name, queue, next_run_at, metadata
FROM /* TEMPLATE: schema */river_periodic_job
ORDER BY id ASC
`

type PeriodicJobGetAllExtRow struct {
	ID        int64
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	Queue     string
	NextRunAt time.Time
	Metadata  []byte
}

func (q *Queries) PeriodicJobGetAllExt(ctx context.Context, db DBTX) ([]*PeriodicJobGetAllExtRow, error) {
	rows, err := db.Query(ctx, periodicJobGetAllExt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*PeriodicJobGetAllExtRow
	for rows.Next() {
		var i PeriodicJobGetAllExtRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.Queue,
			&i.NextRunAt,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const periodicJobGetByIDExt = `-- name: PeriodicJobGetByIDExt :one
SELECT id, created_at, updated_at, name, queue, next_run_at, metadata
FROM /* TEMPLATE: schema */river_periodic_job
WHERE id = $1
`

type PeriodicJobGetByIDExtRow struct {
	ID        int64
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	Queue     string
	NextRunAt time.Time
	Metadata  []byte
}

func (q *Queries) PeriodicJobGetByIDExt(ctx context.Context, db DBTX, id int64) (*PeriodicJobGetByIDExtRow, error) {
	row := db.QueryRow(ctx, periodicJobGetByIDExt, id)
	var i PeriodicJobGetByIDExtRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Queue,
		&i.NextRunAt,
		&i.Metadata,
	)
	return &i, err
}

const periodicJobInsertExt = `-- name: PeriodicJobInsertExt :one
INSERT INTO /* TEMPLATE: schema */river_periodic_job (name, queue, next_run_at, metadata)
VALUES ($1, $2, $3, $4)
RETURNING id, created_at, updated_at, name, queue, next_run_at, metadata
`

type PeriodicJobInsertExtParams struct {
	Name      string
	Queue     string
	NextRunAt time.Time
	Metadata  []byte
}

type PeriodicJobInsertExtRow struct {
	ID        int64
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	Queue     string
	NextRunAt time.Time
	Metadata  []byte
}

func (q *Queries) PeriodicJobInsertExt(ctx context.Context, db DBTX, arg *PeriodicJobInsertExtParams) (*PeriodicJobInsertExtRow, error) {
	row := db.QueryRow(ctx, periodicJobInsertExt,
		arg.Name,
		arg.Queue,
		arg.NextRunAt,
		arg.Metadata,
	)
	var i PeriodicJobInsertExtRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Queue,
		&i.NextRunAt,
		&i.Metadata,
	)
	return &i, err
}

const periodicJobTouchByID = `-- name: PeriodicJobTouchByID :exec
UPDATE /* TEMPLATE: schema */river_periodic_job
SET updated_at = coalesce($1::timestamptz, now())
WHERE id = $2
`

type PeriodicJobTouchByIDParams struct {
	Now *time.Time
	ID  int64
}

func (q *Queries) PeriodicJobTouchByID(ctx context.Context, db DBTX, arg *PeriodicJobTouchByIDParams) error {
	_, err := db.Exec(ctx, periodicJobTouchByID, arg.Now, arg.ID)
	return err
}

const periodicJobUpsertExt = `-- name: PeriodicJobUpsertExt :one
INSERT INTO /* TEMPLATE: schema */river_periodic_job (name, queue, next_run_at, metadata)
VALUES ($1, $2, $3, $4)
ON CONFLICT (name) DO UPDATE
SET queue = EXCLUDED.queue,
    next_run_at = EXCLUDED.next_run_at,
    metadata = EXCLUDED.metadata,
    updated_at = now()
RETURNING id, created_at, updated_at, name, queue, next_run_at, metadata
`

type PeriodicJobUpsertExtParams struct {
	Name      string
	Queue     string
	NextRunAt time.Time
	Metadata  []byte
}

type PeriodicJobUpsertExtRow struct {
	ID        int64
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	Queue     string
	NextRunAt time.Time
	Metadata  []byte
}

func (q *Queries) PeriodicJobUpsertExt(ctx context.Context, db DBTX, arg *PeriodicJobUpsertExtParams) (*PeriodicJobUpsertExtRow, error) {
	row := db.QueryRow(ctx, periodicJobUpsertExt,
		arg.Name,
		arg.Queue,
		arg.NextRunAt,
		arg.Metadata,
	)
	var i PeriodicJobUpsertExtRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Queue,
		&i.NextRunAt,
		&i.Metadata,
	)
	return &i, err
}

const producerDeleteExt = `-- name: ProducerDeleteExt :exec
DELETE FROM /* TEMPLATE: schema */river_producer
WHERE id = $1
`

func (q *Queries) ProducerDeleteExt(ctx context.Context, db DBTX, id int64) error {
	_, err := db.Exec(ctx, producerDeleteExt, id)
	return err
}

const producerDeleteStaleExcludingID = `-- name: ProducerDeleteStaleExcludingID :exec
DELETE FROM /* TEMPLATE: schema */river_producer
WHERE updated_at < $1
  AND id <> $2
`

type ProducerDeleteStaleExcludingIDParams struct {
	StaleUpdatedAtHorizon time.Time
	ID                    int64
}

func (q *Queries) ProducerDeleteStaleExcludingID(ctx context.Context, db DBTX, arg *ProducerDeleteStaleExcludingIDParams) error {
	_, err := db.Exec(ctx, producerDeleteStaleExcludingID, arg.StaleUpdatedAtHorizon, arg.ID)
	return err
}

const producerGetByIDExt = `-- name: ProducerGetByIDExt :one
SELECT id, created_at, updated_at, queue_name, metadata
FROM /* TEMPLATE: schema */river_producer
WHERE id = $1
`

type ProducerGetByIDExtRow struct {
	ID        int64
	CreatedAt time.Time
	UpdatedAt time.Time
	QueueName string
	Metadata  []byte
}

func (q *Queries) ProducerGetByIDExt(ctx context.Context, db DBTX, id int64) (*ProducerGetByIDExtRow, error) {
	row := db.QueryRow(ctx, producerGetByIDExt, id)
	var i ProducerGetByIDExtRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.QueueName,
		&i.Metadata,
	)
	return &i, err
}

const producerInsertOrUpdateExt = `-- name: ProducerInsertOrUpdateExt :one
INSERT INTO /* TEMPLATE: schema */river_producer (id, queue_name, metadata, created_at, updated_at)
VALUES ($1, $2, $3, coalesce($4::timestamptz, now()), coalesce($4::timestamptz, now()))
ON CONFLICT (id) DO UPDATE
SET queue_name = EXCLUDED.queue_name,
    metadata = EXCLUDED.metadata,
    updated_at = EXCLUDED.updated_at
RETURNING id, created_at, updated_at, queue_name, metadata
`

type ProducerInsertOrUpdateExtParams struct {
	ID        int64
	QueueName string
	Metadata  []byte
	Now       *time.Time
}

type ProducerInsertOrUpdateExtRow struct {
	ID        int64
	CreatedAt time.Time
	UpdatedAt time.Time
	QueueName string
	Metadata  []byte
}

func (q *Queries) ProducerInsertOrUpdateExt(ctx context.Context, db DBTX, arg *ProducerInsertOrUpdateExtParams) (*ProducerInsertOrUpdateExtRow, error) {
	row := db.QueryRow(ctx, producerInsertOrUpdateExt,
		arg.ID,
		arg.QueueName,
		arg.Metadata,
		arg.Now,
	)
	var i ProducerInsertOrUpdateExtRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.QueueName,
		&i.Metadata,
	)
	return &i, err
}

const producerKeepAliveUpsert = `-- name: ProducerKeepAliveUpsert :one
INSERT INTO /* TEMPLATE: schema */river_producer (id, queue_name, metadata, created_at, updated_at)
VALUES ($1, $2, '{}'::jsonb, now(), now())
ON CONFLICT (id) DO UPDATE
SET queue_name = EXCLUDED.queue_name,
    updated_at = now()
RETURNING id, created_at, updated_at, queue_name, metadata
`

type ProducerKeepAliveUpsertParams struct {
	ID        int64
	QueueName string
}

type ProducerKeepAliveUpsertRow struct {
	ID        int64
	CreatedAt time.Time
	UpdatedAt time.Time
	QueueName string
	Metadata  []byte
}

func (q *Queries) ProducerKeepAliveUpsert(ctx context.Context, db DBTX, arg *ProducerKeepAliveUpsertParams) (*ProducerKeepAliveUpsertRow, error) {
	row := db.QueryRow(ctx, producerKeepAliveUpsert, arg.ID, arg.QueueName)
	var i ProducerKeepAliveUpsertRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.QueueName,
		&i.Metadata,
	)
	return &i, err
}

const producerListByQueueExt = `-- name: ProducerListByQueueExt :many
SELECT id, queue_name, metadata, updated_at
FROM /* TEMPLATE: schema */river_producer
WHERE queue_name = $1
ORDER BY id ASC
`

type ProducerListByQueueExtRow struct {
	ID        int64
	QueueName string
	Metadata  []byte
	UpdatedAt time.Time
}

func (q *Queries) ProducerListByQueueExt(ctx context.Context, db DBTX, queueName string) ([]*ProducerListByQueueExtRow, error) {
	rows, err := db.Query(ctx, producerListByQueueExt, queueName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ProducerListByQueueExtRow
	for rows.Next() {
		var i ProducerListByQueueExtRow
		if err := rows.Scan(
			&i.ID,
			&i.QueueName,
			&i.Metadata,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const producerUpdateExt = `-- name: ProducerUpdateExt :one
UPDATE /* TEMPLATE: schema */river_producer
SET metadata = $1,
    updated_at = coalesce($2::timestamptz, now())
WHERE id = $3
RETURNING id, created_at, updated_at, queue_name, metadata
`

type ProducerUpdateExtParams struct {
	Metadata  []byte
	UpdatedAt *time.Time
	ID        int64
}

type ProducerUpdateExtRow struct {
	ID        int64
	CreatedAt time.Time
	UpdatedAt time.Time
	QueueName string
	Metadata  []byte
}

func (q *Queries) ProducerUpdateExt(ctx context.Context, db DBTX, arg *ProducerUpdateExtParams) (*ProducerUpdateExtRow, error) {
	row := db.QueryRow(ctx, producerUpdateExt, arg.Metadata, arg.UpdatedAt, arg.ID)
	var i ProducerUpdateExtRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.QueueName,
		&i.Metadata,
	)
	return &i, err
}

const queueGetMetadataForInsert = `-- name: QueueGetMetadataForInsert :many
SELECT name, metadata
FROM /* TEMPLATE: schema */river_queue
WHERE name = any($1::text[])
`

type QueueGetMetadataForInsertRow struct {
	Name     string
	Metadata []byte
}

func (q *Queries) QueueGetMetadataForInsert(ctx context.Context, db DBTX, queueNames []string) ([]*QueueGetMetadataForInsertRow, error) {
	rows, err := db.Query(ctx, queueGetMetadataForInsert, queueNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*QueueGetMetadataForInsertRow
	for rows.Next() {
		var i QueueGetMetadataForInsertRow
		if err := rows.Scan(&i.Name, &i.Metadata); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sequenceAppend = `-- name: SequenceAppend :exec
INSERT INTO /* TEMPLATE: schema */river_sequence (queue, key, latest_job_id, created_at, updated_at)
VALUES ($1, $2, $3, now(), now())
ON CONFLICT (queue, key) DO UPDATE
SET latest_job_id = greatest(/* TEMPLATE: schema */river_sequence.latest_job_id, EXCLUDED.latest_job_id),
    updated_at = now()
`

type SequenceAppendParams struct {
	Queue       string
	Key         string
	LatestJobID int64
}

func (q *Queries) SequenceAppend(ctx context.Context, db DBTX, arg *SequenceAppendParams) error {
	_, err := db.Exec(ctx, sequenceAppend, arg.Queue, arg.Key, arg.LatestJobID)
	return err
}

const sequenceListExt = `-- name: SequenceListExt :many
SELECT id, created_at, updated_at, queue, key, latest_job_id
FROM /* TEMPLATE: schema */river_sequence
WHERE queue = $1
ORDER BY updated_at DESC
LIMIT $2
`

type SequenceListExtParams struct {
	Queue string
	Max   int32
}

type SequenceListExtRow struct {
	ID          int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Queue       string
	Key         string
	LatestJobID int64
}

func (q *Queries) SequenceListExt(ctx context.Context, db DBTX, arg *SequenceListExtParams) ([]*SequenceListExtRow, error) {
	rows, err := db.Query(ctx, sequenceListExt, arg.Queue, arg.Max)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*SequenceListExtRow
	for rows.Next() {
		var i SequenceListExtRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Queue,
			&i.Key,
			&i.LatestJobID,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sequencePromote = `-- name: SequencePromote :many
WITH promotable AS (
    SELECT j.id, j.queue
    FROM /* TEMPLATE: schema */river_job j
    WHERE j.queue = $1
      AND j.state = 'pending'
      AND coalesce(j.sequence_key, j.metadata->>'sequence_key') IS NOT NULL
      AND NOT EXISTS (
        SELECT 1
        FROM /* TEMPLATE: schema */river_job prev
        WHERE prev.queue = j.queue
          AND coalesce(prev.sequence_key, prev.metadata->>'sequence_key') = coalesce(j.sequence_key, j.metadata->>'sequence_key')
          AND prev.id < j.id
          AND (
            prev.state IN ('available', 'pending', 'retryable', 'running', 'scheduled')
            OR (prev.state = 'cancelled' AND NOT coalesce((j.metadata->>'sequence_continue_on_cancelled')::boolean, false))
            OR (prev.state = 'discarded' AND NOT coalesce((j.metadata->>'sequence_continue_on_discarded')::boolean, false))
          )
      )
      AND NOT EXISTS (
        SELECT 1
        FROM /* TEMPLATE: schema */river_job same_seq_pending
        WHERE same_seq_pending.queue = j.queue
          AND same_seq_pending.state = 'pending'
          AND coalesce(same_seq_pending.sequence_key, same_seq_pending.metadata->>'sequence_key') = coalesce(j.sequence_key, j.metadata->>'sequence_key')
          AND same_seq_pending.id < j.id
      )
    ORDER BY j.id ASC
    LIMIT $2
)
UPDATE /* TEMPLATE: schema */river_job j
SET state = 'available',
    scheduled_at = now()
FROM promotable
WHERE j.id = promotable.id
RETURNING j.queue
`

type SequencePromoteParams struct {
	Queue string
	Max   int32
}

func (q *Queries) SequencePromote(ctx context.Context, db DBTX, arg *SequencePromoteParams) ([]string, error) {
	rows, err := db.Query(ctx, sequencePromote, arg.Queue, arg.Max)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var queue string
		if err := rows.Scan(&queue); err != nil {
			return nil, err
		}
		items = append(items, queue)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sequencePromoteFromTable = `-- name: SequencePromoteFromTable :many
SELECT DISTINCT queue
FROM /* TEMPLATE: schema */river_sequence
ORDER BY queue ASC
LIMIT $1
`

func (q *Queries) SequencePromoteFromTable(ctx context.Context, db DBTX, max int32) ([]string, error) {
	rows, err := db.Query(ctx, sequencePromoteFromTable, max)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var queue string
		if err := rows.Scan(&queue); err != nil {
			return nil, err
		}
		items = append(items, queue)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const workflowCancelByIDs = `-- name: WorkflowCancelByIDs :many
UPDATE /* TEMPLATE: schema */river_job
SET state = 'cancelled',
    finalized_at = now()
WHERE id = any($1::bigint[])
  AND state IN ('available', 'pending', 'retryable', 'scheduled')
RETURNING id
`

func (q *Queries) WorkflowCancelByIDs(ctx context.Context, db DBTX, ids []int64) ([]int64, error) {
	rows, err := db.Query(ctx, workflowCancelByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const workflowCancelByWorkflowID = `-- name: WorkflowCancelByWorkflowID :many
UPDATE /* TEMPLATE: schema */river_job
SET state = 'cancelled',
    finalized_at = now()
WHERE coalesce(workflow_id, metadata->>'workflow_id') = $1
  AND state IN ('available', 'pending', 'retryable', 'scheduled')
RETURNING id
`

func (q *Queries) WorkflowCancelByWorkflowID(ctx context.Context, db DBTX, workflowID pgtype.Text) ([]int64, error) {
	rows, err := db.Query(ctx, workflowCancelByWorkflowID, workflowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const workflowCancelWithFailedDepsByIDs = `-- name: WorkflowCancelWithFailedDepsByIDs :many
UPDATE /* TEMPLATE: schema */river_job
SET state = 'cancelled',
    finalized_at = coalesce($1::timestamptz, now()),
    metadata = metadata || jsonb_build_object(
        'workflow_deps_failed_at', to_jsonb(coalesce($1::timestamptz, now()))
    )
WHERE id = any($2::bigint[])
  AND state IN ('available', 'pending', 'retryable', 'scheduled')
RETURNING id
`

type WorkflowCancelWithFailedDepsByIDsParams struct {
	WorkflowDepsFailedAt *time.Time
	IDs                  []int64
}

func (q *Queries) WorkflowCancelWithFailedDepsByIDs(ctx context.Context, db DBTX, arg *WorkflowCancelWithFailedDepsByIDsParams) ([]int64, error) {
	rows, err := db.Query(ctx, workflowCancelWithFailedDepsByIDs, arg.WorkflowDepsFailedAt, arg.IDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const workflowCountRunning = `-- name: WorkflowCountRunning :one
SELECT count(*)
FROM /* TEMPLATE: schema */river_job
WHERE coalesce(workflow_id, metadata->>'workflow_id') = $1
  AND state = 'running'
`

func (q *Queries) WorkflowCountRunning(ctx context.Context, db DBTX, workflowID pgtype.Text) (int64, error) {
	row := db.QueryRow(ctx, workflowCountRunning, workflowID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const workflowGetPendingIDs = `-- name: WorkflowGetPendingIDs :many
SELECT id, coalesce(workflow_task_name, metadata->>'workflow_task_name', '') AS task
FROM /* TEMPLATE: schema */river_job
WHERE coalesce(workflow_id, metadata->>'workflow_id') = $1
  AND state = 'pending'
ORDER BY id ASC
`

type WorkflowGetPendingIDsRow struct {
	ID   int64
	Task string
}

func (q *Queries) WorkflowGetPendingIDs(ctx context.Context, db DBTX, workflowID pgtype.Text) ([]*WorkflowGetPendingIDsRow, error) {
	rows, err := db.Query(ctx, workflowGetPendingIDs, workflowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*WorkflowGetPendingIDsRow
	for rows.Next() {
		var i WorkflowGetPendingIDsRow
		if err := rows.Scan(&i.ID, &i.Task); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const workflowJobGetByTaskNameID = `-- name: WorkflowJobGetByTaskNameID :one
SELECT id
FROM /* TEMPLATE: schema */river_job
WHERE coalesce(workflow_id, metadata->>'workflow_id') = $1
  AND coalesce(workflow_task_name, metadata->>'workflow_task_name') = $2
ORDER BY id DESC
LIMIT 1
`

type WorkflowJobGetByTaskNameIDParams struct {
	WorkflowID pgtype.Text
	TaskName   pgtype.Text
}

func (q *Queries) WorkflowJobGetByTaskNameID(ctx context.Context, db DBTX, arg *WorkflowJobGetByTaskNameIDParams) (int64, error) {
	row := db.QueryRow(ctx, workflowJobGetByTaskNameID, arg.WorkflowID, arg.TaskName)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const workflowJobListIDs = `-- name: WorkflowJobListIDs :many
SELECT id
FROM /* TEMPLATE: schema */river_job
WHERE coalesce(workflow_id, metadata->>'workflow_id') = $1
ORDER BY id ASC
`

func (q *Queries) WorkflowJobListIDs(ctx context.Context, db DBTX, workflowID pgtype.Text) ([]int64, error) {
	rows, err := db.Query(ctx, workflowJobListIDs, workflowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const workflowListActive = `-- name: WorkflowListActive :many
SELECT workflow_id, min(created_at) AS created_at, max(created_at) AS updated_at
FROM (
    SELECT coalesce(workflow_id, metadata->>'workflow_id') AS workflow_id, created_at, state
    FROM /* TEMPLATE: schema */river_job
    WHERE coalesce(workflow_id, metadata->>'workflow_id') IS NOT NULL
) grouped
GROUP BY workflow_id
HAVING bool_or(state NOT IN ('cancelled','completed','discarded'))
ORDER BY max(created_at) DESC
LIMIT $1
`

type WorkflowListActiveRow struct {
	WorkflowID pgtype.Text
	CreatedAt  interface{}
	UpdatedAt  interface{}
}

func (q *Queries) WorkflowListActive(ctx context.Context, db DBTX, max int32) ([]*WorkflowListActiveRow, error) {
	rows, err := db.Query(ctx, workflowListActive, max)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*WorkflowListActiveRow
	for rows.Next() {
		var i WorkflowListActiveRow
		if err := rows.Scan(&i.WorkflowID, &i.CreatedAt, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const workflowListAll = `-- name: WorkflowListAll :many
SELECT workflow_id, min(created_at) AS created_at, max(created_at) AS updated_at
FROM (
    SELECT coalesce(workflow_id, metadata->>'workflow_id') AS workflow_id, created_at, state
    FROM /* TEMPLATE: schema */river_job
    WHERE coalesce(workflow_id, metadata->>'workflow_id') IS NOT NULL
) grouped
GROUP BY workflow_id
ORDER BY max(created_at) DESC
LIMIT $1
`

type WorkflowListAllRow struct {
	WorkflowID pgtype.Text
	CreatedAt  interface{}
	UpdatedAt  interface{}
}

func (q *Queries) WorkflowListAll(ctx context.Context, db DBTX, max int32) ([]*WorkflowListAllRow, error) {
	rows, err := db.Query(ctx, workflowListAll, max)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*WorkflowListAllRow
	for rows.Next() {
		var i WorkflowListAllRow
		if err := rows.Scan(&i.WorkflowID, &i.CreatedAt, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const workflowListInactive = `-- name: WorkflowListInactive :many
SELECT workflow_id, min(created_at) AS created_at, max(created_at) AS updated_at
FROM (
    SELECT coalesce(workflow_id, metadata->>'workflow_id') AS workflow_id, created_at, state
    FROM /* TEMPLATE: schema */river_job
    WHERE coalesce(workflow_id, metadata->>'workflow_id') IS NOT NULL
) grouped
GROUP BY workflow_id
HAVING NOT bool_or(state NOT IN ('cancelled','completed','discarded'))
ORDER BY max(created_at) DESC
LIMIT $1
`

type WorkflowListInactiveRow struct {
	WorkflowID pgtype.Text
	CreatedAt  interface{}
	UpdatedAt  interface{}
}

func (q *Queries) WorkflowListInactive(ctx context.Context, db DBTX, max int32) ([]*WorkflowListInactiveRow, error) {
	rows, err := db.Query(ctx, workflowListInactive, max)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*WorkflowListInactiveRow
	for rows.Next() {
		var i WorkflowListInactiveRow
		if err := rows.Scan(&i.WorkflowID, &i.CreatedAt, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const workflowLoadDepTasksAndIDs = `-- name: WorkflowLoadDepTasksAndIDs :many
SELECT coalesce(workflow_task_name, metadata->>'workflow_task_name') AS task, id
FROM /* TEMPLATE: schema */river_job
WHERE coalesce(workflow_id, metadata->>'workflow_id') = $1
  AND coalesce(workflow_task_name, metadata->>'workflow_task_name') = any($2::text[])
`

type WorkflowLoadDepTasksAndIDsParams struct {
	WorkflowID pgtype.Text
	TaskNames  []string
}

type WorkflowLoadDepTasksAndIDsRow struct {
	Task pgtype.Text
	ID   int64
}

func (q *Queries) WorkflowLoadDepTasksAndIDs(ctx context.Context, db DBTX, arg *WorkflowLoadDepTasksAndIDsParams) ([]*WorkflowLoadDepTasksAndIDsRow, error) {
	rows, err := db.Query(ctx, workflowLoadDepTasksAndIDs, arg.WorkflowID, arg.TaskNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*WorkflowLoadDepTasksAndIDsRow
	for rows.Next() {
		var i WorkflowLoadDepTasksAndIDsRow
		if err := rows.Scan(&i.Task, &i.ID); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const workflowLoadJobsWithDeps = `-- name: WorkflowLoadJobsWithDeps :many
SELECT id,
       coalesce(workflow_task_name, metadata->>'workflow_task_name', '') AS task,
       coalesce(nullif(workflow_deps, '{}'::text[])::text, (metadata->'workflow_deps')::text, '{}') AS deps_raw
FROM /* TEMPLATE: schema */river_job
WHERE coalesce(workflow_id, metadata->>'workflow_id') = $1
`

type WorkflowLoadJobsWithDepsRow struct {
	ID      int64
	Task    string
	DepsRaw interface{}
}

func (q *Queries) WorkflowLoadJobsWithDeps(ctx context.Context, db DBTX, workflowID pgtype.Text) ([]*WorkflowLoadJobsWithDepsRow, error) {
	rows, err := db.Query(ctx, workflowLoadJobsWithDeps, workflowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*WorkflowLoadJobsWithDepsRow
	for rows.Next() {
		var i WorkflowLoadJobsWithDepsRow
		if err := rows.Scan(&i.ID, &i.Task, &i.DepsRaw); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const workflowLoadTaskDepsByJobID = `-- name: WorkflowLoadTaskDepsByJobID :one
SELECT coalesce(nullif(workflow_deps, '{}'::text[])::text, (metadata->'workflow_deps')::text, '{}')
FROM /* TEMPLATE: schema */river_job
WHERE id = $1
`

func (q *Queries) WorkflowLoadTaskDepsByJobID(ctx context.Context, db DBTX, id int64) (interface{}, error) {
	row := db.QueryRow(ctx, workflowLoadTaskDepsByJobID, id)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const workflowLoadTasksByNames = `-- name: WorkflowLoadTasksByNames :many
SELECT coalesce(workflow_task_name, metadata->>'workflow_task_name','') AS task,
       coalesce(nullif(workflow_deps, '{}'::text[])::text, (metadata->'workflow_deps')::text, '{}') AS deps_raw
FROM /* TEMPLATE: schema */river_job
WHERE coalesce(workflow_id, metadata->>'workflow_id') = $1
  AND coalesce(workflow_task_name, metadata->>'workflow_task_name') = any($2::text[])
`

type WorkflowLoadTasksByNamesParams struct {
	WorkflowID pgtype.Text
	TaskNames  []string
}

type WorkflowLoadTasksByNamesRow struct {
	Task    string
	DepsRaw interface{}
}

func (q *Queries) WorkflowLoadTasksByNames(ctx context.Context, db DBTX, arg *WorkflowLoadTasksByNamesParams) ([]*WorkflowLoadTasksByNamesRow, error) {
	rows, err := db.Query(ctx, workflowLoadTasksByNames, arg.WorkflowID, arg.TaskNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*WorkflowLoadTasksByNamesRow
	for rows.Next() {
		var i WorkflowLoadTasksByNamesRow
		if err := rows.Scan(&i.Task, &i.DepsRaw); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const workflowRetryByIDMany = `-- name: WorkflowRetryByIDMany :many
UPDATE /* TEMPLATE: schema */river_job
SET state = 'available',
    attempt = CASE WHEN $1::boolean THEN 0 ELSE attempt END,
    attempted_at = CASE WHEN $1::boolean THEN NULL ELSE attempted_at END,
    attempted_by = CASE WHEN $1::boolean THEN NULL ELSE attempted_by END,
    errors = CASE WHEN $1::boolean THEN '{}'::jsonb[] ELSE errors END,
    finalized_at = NULL,
    max_attempts = CASE WHEN $1::boolean THEN max_attempts WHEN attempt = max_attempts THEN max_attempts + 1 ELSE max_attempts END,
    metadata = CASE WHEN $1::boolean THEN metadata - 'output' ELSE metadata END,
    scheduled_at = coalesce($2::timestamptz, now())
WHERE id = any($3::bigint[])
RETURNING id
`

type WorkflowRetryByIDManyParams struct {
	ResetHistory bool
	Now          *time.Time
	IDs          []int64
}

func (q *Queries) WorkflowRetryByIDMany(ctx context.Context, db DBTX, arg *WorkflowRetryByIDManyParams) ([]int64, error) {
	rows, err := db.Query(ctx, workflowRetryByIDMany, arg.ResetHistory, arg.Now, arg.IDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const workflowSetPendingByIDMany = `-- name: WorkflowSetPendingByIDMany :many
UPDATE /* TEMPLATE: schema */river_job
SET state = 'pending'
WHERE id = any($1::bigint[])
  AND state = 'available'
RETURNING id
`

func (q *Queries) WorkflowSetPendingByIDMany(ctx context.Context, db DBTX, ids []int64) ([]int64, error) {
	rows, err := db.Query(ctx, workflowSetPendingByIDMany, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const workflowStageJobsByIDMany = `-- name: WorkflowStageJobsByIDMany :many
UPDATE /* TEMPLATE: schema */river_job
SET state = 'available',
    scheduled_at = now()
WHERE id = any($1::bigint[])
  AND state = 'pending'
RETURNING id
`

func (q *Queries) WorkflowStageJobsByIDMany(ctx context.Context, db DBTX, ids []int64) ([]int64, error) {
	rows, err := db.Query(ctx, workflowStageJobsByIDMany, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
